### PR TITLE
Crenshaw's Fun

### PR DESCRIPTION
**Pull request by Crenshaw1312**
# Radeon has nothing fun
Yea, so I'm taking a lot of commands from my small-time/personal bot Jackson and adding them to here, I'll update this later bc rn I just wanna get started on this. Hope to contribute more in the future and bug fix things as needed

### CODE REVIEW

**Comment by Crenshaw1312** [comment]
hi

**Comment by Crenshaw1312** [comment]
## Causal Update - 1
* Fixed some things when attempting to self-host
* Made fun section
* Added fun to reload
* Added myself to contributors and readme
* Added YoutubeKey to config
* Song Available command
* 8ball command
* Truth command
* Dare command
* Would you Rather command
> Added Packages: none added

> Total New Commands: 5

**Review by devnote-dev — CHANGES_REQUESTED** [review]
The changes look good, a few things though:

- truth/dare commands seem a bit pointless, the Tod bot is much better for that
- choose function doesn't need to be exported since it won't be used in more than one file
- package-lock shouldn't be in the gitignore

**Comment by Crenshaw1312** [comment]
okay coolio,
* I'm leaving the truth or dare commands because not every server is going to have the tod bot.
* The choose function is used with some other commands I'm yet to add
* I'll fix that.... Just didn't like looking at the forever-highlighted file

**Review by devnote-dev — CHANGES_REQUESTED** [review]
Commands are looking good, reddit command should return a message upon error though

**Review by devnote-dev — APPROVED** [review]

**Pull request merged**
